// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $app_middleware from "./routes/app/_middleware.ts";
import * as $app_account_id_ from "./routes/app/account/[id].tsx";
import * as $app_account_add from "./routes/app/account/add.tsx";
import * as $app_account_index from "./routes/app/account/index.tsx";
import * as $app_api_record from "./routes/app/api/record.ts";
import * as $app_record_id_ from "./routes/app/record/[id].tsx";
import * as $app_record_index from "./routes/app/record/index.tsx";
import * as $app_user_id_ from "./routes/app/user/[id].tsx";
import * as $app_user_add from "./routes/app/user/add.tsx";
import * as $app_user_index from "./routes/app/user/index.tsx";
import * as $index from "./routes/index.tsx";
import * as $Counter from "./islands/Counter.tsx";
import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/app/_middleware.ts": $app_middleware,
    "./routes/app/account/[id].tsx": $app_account_id_,
    "./routes/app/account/add.tsx": $app_account_add,
    "./routes/app/account/index.tsx": $app_account_index,
    "./routes/app/api/record.ts": $app_api_record,
    "./routes/app/record/[id].tsx": $app_record_id_,
    "./routes/app/record/index.tsx": $app_record_index,
    "./routes/app/user/[id].tsx": $app_user_id_,
    "./routes/app/user/add.tsx": $app_user_add,
    "./routes/app/user/index.tsx": $app_user_index,
    "./routes/index.tsx": $index,
  },
  islands: {
    "./islands/Counter.tsx": $Counter,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
